#!/bin/sh
set -eu

expected_team_id="QS3GC3CT43"

# Xcode Cloud checks out source only; the Xcode project is generated locally.
if ! command -v xcodegen >/dev/null 2>&1; then
  if command -v brew >/dev/null 2>&1; then
    brew install xcodegen
  else
    echo "xcodegen is required to generate A Playa Named Gus.xcodeproj" >&2
    exit 69
  fi
fi

if [ "${CI_XCODE_CLOUD:-}" = "TRUE" ]; then
  cloud_team_id="${CI_TEAM_ID:-$expected_team_id}"
  if [ "$cloud_team_id" != "$expected_team_id" ]; then
    echo "Xcode Cloud is running with Team ID $cloud_team_id, expected $expected_team_id." >&2
    exit 65
  fi

  cat > Config/Local.xcconfig <<EOF
// Generated by ci_scripts/ci_post_clone.sh in Xcode Cloud.
DEVELOPMENT_TEAM = $expected_team_id
CODE_SIGN_STYLE = Automatic
CODE_SIGN_IDENTITY =
CODE_SIGNING_REQUIRED = YES
CODE_SIGNING_ALLOWED = YES
GUS_IOS_PROVISIONING_PROFILE_SPECIFIER =
GUS_TVOS_PROVISIONING_PROFILE_SPECIFIER =
GUS_TOPSHELF_TVOS_PROVISIONING_PROFILE_SPECIFIER =
GUS_VISIONOS_PROVISIONING_PROFILE_SPECIFIER =
GUS_MACOS_PROVISIONING_PROFILE_SPECIFIER =
EOF
fi

xcodegen generate
